/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package akura;

import java.awt.Color;
import java.awt.Toolkit;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Pasindu01
 */
public class Classes extends javax.swing.JFrame {

    /**
     * Creates new form Classes
     */
    
    DefaultTableModel model = new DefaultTableModel();
    
    public Classes() {
        initComponents();
        
        setIcon();
        
        tblClassData.getTableHeader().setOpaque(false);
        tblClassData.getTableHeader().setBackground(new Color(196, 88, 53));
        tblClassData.getTableHeader().setForeground(new Color(255, 255, 255));
        tblClassData.setRowHeight(25);
        
        
        jPanel2.setBackground(new Color(51,6,149));
        jPanel3.setBackground(new Color(51,51,51));
        overviewPane.setVisible(true);
        createClassPane.setVisible(false);
         
//        Overview Table Data
        tblClass();
        
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }
    

    
    
//    ArrayList for Data
    public ArrayList<ClassData> dataTec(){
            ArrayList<ClassData> classData = new ArrayList<>();
            
            try {
                Connection con = DatabaseConnection.getcon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from class c inner join subject s on c.Subject = s.Subject_ID inner join teacher t on t.Teacher_ID = c.Teacher");
                ClassData data;
                while(rs.next()){
                    data = new ClassData(rs.getString("c.Class_ID"),rs.getString("c.Class_Name"),rs.getString("c.Grade"),rs.getString("t.Name_with_initials"), rs.getString("s.Subject_Name"),rs.getString("c.Sche_time"), rs.getString("c.Schedule_date"), rs.getDouble("c.Class_Fee"));
                    classData.add(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        return classData;
    }
    
//    Data set to tblClassData Table
    public void tblClass(){
        ArrayList<ClassData> list = dataTec();
        model = (DefaultTableModel) tblClassData.getModel();
        
        Object row[] = new Object[8];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getClass_ID();
            row[1] = list.get(i).getClass_Name();
            row[2] = list.get(i).getGrade();
            row[3] = list.get(i).getName_with_initials();
            row[4] = list.get(i).getSubject_Name();
            row[5] = list.get(i).getSche_time();
            row[6] = list.get(i).getSchedule_date();
            row[7] = list.get(i).getClass_Fee();
            model.addRow(row);
        }
    }
    
//    Searc from table
    private void search(String str){
        model = (DefaultTableModel) tblClassData.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        tblClassData.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        createClassPane = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtClassID = new javax.swing.JTextField();
        txtTeacID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTeacName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSubID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSubName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtClassName = new javax.swing.JTextField();
        txtGrade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        chkSun = new javax.swing.JCheckBox();
        chkMon = new javax.swing.JCheckBox();
        chkTue = new javax.swing.JCheckBox();
        chkWed = new javax.swing.JCheckBox();
        chkThr = new javax.swing.JCheckBox();
        chkSat = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtTime = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        chkFri = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        txtAddClassFee = new javax.swing.JTextField();
        txtAddComision = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        overviewPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClassData = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnClassesDelete = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Class Handling | Akura");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create Class");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_google_classroom_32px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(42, 42, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 154, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_ratings_24px_1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Overiew");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(714, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 60));

        createClassPane.setBackground(new java.awt.Color(255, 255, 255));
        createClassPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dateChooserPanel1.setCurrentView(new datechooser.view.appearance.AppearancesList("Dali",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Dialog", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserPanel1.setCalendarBackground(new java.awt.Color(0, 0, 0));
    dateChooserPanel1.setNavigateFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(dateChooserPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(dateChooserPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    createClassPane.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 204, 490, 300));

    jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("Calender");
    createClassPane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 492, 40));

    jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel6.setText("Class ID");
    createClassPane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 48, 184, 35));

    txtClassID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    createClassPane.add(txtClassID, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 48, 344, 33));

    txtTeacID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    txtTeacID.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            txtTeacIDKeyPressed(evt);
        }
    });
    createClassPane.add(txtTeacID, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 96, 344, 33));

    jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel7.setText("Teacher ID");
    createClassPane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 96, 184, 35));

    txtTeacName.setEditable(false);
    txtTeacName.setBackground(new java.awt.Color(255, 255, 255));
    txtTeacName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    createClassPane.add(txtTeacName, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 144, 344, 33));

    jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel8.setText("Teacher Name");
    createClassPane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 144, 184, 35));

    txtSubID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    txtSubID.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            txtSubIDKeyPressed(evt);
        }
    });
    createClassPane.add(txtSubID, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 192, 344, 33));

    jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel9.setText("Subject ID");
    createClassPane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 192, 184, 35));

    txtSubName.setEditable(false);
    txtSubName.setBackground(new java.awt.Color(255, 255, 255));
    txtSubName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    createClassPane.add(txtSubName, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 240, 344, 33));

    jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel10.setText("Subject Name");
    createClassPane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 240, 184, 35));

    jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel11.setText("Class Name");
    createClassPane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 288, 184, 35));

    txtClassName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    createClassPane.add(txtClassName, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 288, 344, 33));

    txtGrade.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    createClassPane.add(txtGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 336, 344, 33));

    jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel12.setText("Grade");
    createClassPane.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 336, 184, 35));

    jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel13.setText("Schedule Date");
    createClassPane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 384, 126, 35));

    chkSun.setBackground(new java.awt.Color(255, 255, 255));
    buttonGroup1.add(chkSun);
    chkSun.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    chkSun.setText("Sun");
    createClassPane.add(chkSun, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, 33));

    chkMon.setBackground(new java.awt.Color(255, 255, 255));
    buttonGroup1.add(chkMon);
    chkMon.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    chkMon.setText("Mon");
    createClassPane.add(chkMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, 33));

    chkTue.setBackground(new java.awt.Color(255, 255, 255));
    buttonGroup1.add(chkTue);
    chkTue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    chkTue.setText("Tue");
    createClassPane.add(chkTue, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, 33));

    chkWed.setBackground(new java.awt.Color(255, 255, 255));
    buttonGroup1.add(chkWed);
    chkWed.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    chkWed.setText("Wed");
    createClassPane.add(chkWed, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, 33));

    chkThr.setBackground(new java.awt.Color(255, 255, 255));
    buttonGroup1.add(chkThr);
    chkThr.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    chkThr.setText("Thr");
    createClassPane.add(chkThr, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, 33));

    chkSat.setBackground(new java.awt.Color(255, 255, 255));
    buttonGroup1.add(chkSat);
    chkSat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    chkSat.setText("Sat");
    createClassPane.add(chkSat, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, 33));

    jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel14.setText("Schedule Time");
    createClassPane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 425, 184, 35));

    jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel15.setText("Create New Class");
    createClassPane.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 0, 428, 30));

    jButton5.setBackground(new java.awt.Color(0, 0, 255));
    jButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jButton5.setForeground(new java.awt.Color(255, 255, 255));
    jButton5.setText("Save");
    jButton5.setBorderPainted(false);
    jButton5.setFocusPainted(false);
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });
    createClassPane.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 472, 99, 42));

    jButton6.setBackground(new java.awt.Color(0, 0, 255));
    jButton6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jButton6.setForeground(new java.awt.Color(255, 255, 255));
    jButton6.setText("Reset");
    jButton6.setBorderPainted(false);
    jButton6.setFocusPainted(false);
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });
    createClassPane.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 472, 97, 42));

    txtTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("H:mm"))));
    txtTime.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    createClassPane.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 426, 235, 33));

    jLabel17.setBackground(new java.awt.Color(255, 255, 255));
    jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel17.setText("HH : MM : SS");
    createClassPane.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 425, -1, 35));

    chkFri.setBackground(new java.awt.Color(255, 255, 255));
    buttonGroup1.add(chkFri);
    chkFri.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    chkFri.setText("Fri");
    createClassPane.add(chkFri, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, -1, 33));

    jLabel18.setBackground(new java.awt.Color(255, 255, 255));
    jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel18.setText("Class Fee        Rs.");
    createClassPane.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 139, 28));

    txtAddClassFee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    createClassPane.add(txtAddClassFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 316, 30));

    txtAddComision.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    createClassPane.add(txtAddComision, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, 243, 30));

    jLabel19.setBackground(new java.awt.Color(255, 255, 255));
    jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel19.setText("Institute Commission Rate (%)");
    createClassPane.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 216, 28));

    getContentPane().add(createClassPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1140, 520));

    overviewPane.setBackground(new java.awt.Color(255, 255, 255));
    overviewPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    tblClassData.setAutoCreateRowSorter(true);
    tblClassData.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Class ID", "Class Name", "Grade", "Subject", "Schedule Time", "Schedule Date", "Teacher", "Class Fee"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    tblClassData.setFillsViewportHeight(true);
    tblClassData.setFocusable(false);
    tblClassData.setIntercellSpacing(new java.awt.Dimension(0, 0));
    tblClassData.setRowHeight(25);
    tblClassData.setSelectionBackground(new java.awt.Color(102, 153, 255));
    tblClassData.setShowVerticalLines(false);
    tblClassData.getTableHeader().setReorderingAllowed(false);
    jScrollPane1.setViewportView(tblClassData);
    if (tblClassData.getColumnModel().getColumnCount() > 0) {
        tblClassData.getColumnModel().getColumn(0).setResizable(false);
        tblClassData.getColumnModel().getColumn(1).setResizable(false);
        tblClassData.getColumnModel().getColumn(2).setResizable(false);
        tblClassData.getColumnModel().getColumn(3).setResizable(false);
        tblClassData.getColumnModel().getColumn(4).setResizable(false);
        tblClassData.getColumnModel().getColumn(5).setResizable(false);
        tblClassData.getColumnModel().getColumn(6).setResizable(false);
        tblClassData.getColumnModel().getColumn(7).setResizable(false);
    }

    overviewPane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 60, 1102, 390));

    jButton2.setBackground(new java.awt.Color(0, 0, 255));
    jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jButton2.setForeground(new java.awt.Color(255, 255, 255));
    jButton2.setText("Update");
    jButton2.setBorderPainted(false);
    jButton2.setFocusPainted(false);
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    overviewPane.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 460, 116, 43));

    jButton4.setBackground(new java.awt.Color(0, 0, 255));
    jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jButton4.setForeground(new java.awt.Color(255, 255, 255));
    jButton4.setText("View");
    jButton4.setBorderPainted(false);
    jButton4.setFocusPainted(false);
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });
    overviewPane.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 118, 43));

    jLabel16.setBackground(new java.awt.Color(255, 255, 255));
    jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel16.setText("Search");
    overviewPane.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 140, 30));

    txtSearch.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    txtSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            txtSearchKeyReleased(evt);
        }
    });
    overviewPane.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 380, 30));

    btnClassesDelete.setBackground(new java.awt.Color(0, 0, 255));
    btnClassesDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    btnClassesDelete.setForeground(new java.awt.Color(255, 255, 255));
    btnClassesDelete.setText("Delete");
    btnClassesDelete.setBorderPainted(false);
    btnClassesDelete.setFocusPainted(false);
    btnClassesDelete.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnClassesDeleteActionPerformed(evt);
        }
    });
    overviewPane.add(btnClassesDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 105, 43));

    getContentPane().add(overviewPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1140, 520));

    jButton3.setBackground(new java.awt.Color(255, 0, 0));
    jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    jButton3.setForeground(new java.awt.Color(255, 255, 255));
    jButton3.setText("Back");
    jButton3.setBorderPainted(false);
    jButton3.setFocusPainted(false);
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 610, 100, 40));

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        createClassPane.setVisible(true);
        overviewPane.setVisible(false);
        
        jPanel3.setBackground(new Color(51,6,149));
        jPanel2.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        overviewPane.setVisible(true);
        createClassPane.setVisible(false);
        
        jPanel2.setBackground(new Color(51,6,149));
        jPanel3.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel2MouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String text = txtSearch.getText().toUpperCase();
        search(text);
    }//GEN-LAST:event_txtSearchKeyReleased
   
// Code for Class Data view from Table
    viewClassData classData  = new viewClassData();
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        classData.jButton6.setVisible(false);
        classData.lblViewClassTitle.setText("Class Information");
        
        try {
            model = (DefaultTableModel) tblClassData.getModel();
            int row = tblClassData.getSelectedRow();
            String id = model.getValueAt(row, 0).toString();
            classData.txtCVClassID.setText(id);
            classData.txtCVClassName.setText(model.getValueAt(row, 1).toString());
            classData.txtCVGrade.setText(model.getValueAt(row, 2).toString());
            classData.txtCVSubName.setText(model.getValueAt(row, 3).toString());
            classData.txtCVTime.setText(model.getValueAt(row, 4).toString());
            classData.txtCVDate.setText(model.getValueAt(row, 5).toString());
            classData.txtCVTeaName.setText(model.getValueAt(row, 6).toString());
            classData.txtCVClassFee.setText(model.getValueAt(row, 7).toString());

            try {
                Connection con = DatabaseConnection.getcon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select Teacher, Subject, Commision_Rate from class where Class_ID = '"+id+"'");
                while(rs.next()){
                    classData.txtCVTeaID.setText(rs.getString("Teacher"));
                    classData.txtCVSubID.setText(rs.getString("Subject"));
                    classData.txtCVCommision.setText(rs.getString("Commision_Rate"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Something went gone wrong...!", "Error", JOptionPane.ERROR_MESSAGE);
//                System.out.println(e);
            }
            classData.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Please select a row from table...");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        classData.jButton6.setVisible(true);
        
        classData.lblViewClassTitle.setText("Edit Class Information");
        
        try {
            model = (DefaultTableModel) tblClassData.getModel();
            int row = tblClassData.getSelectedRow();
            String id = model.getValueAt(row, 0).toString();
            classData.txtCVClassID.setText(id);
            classData.txtCVClassName.setText(model.getValueAt(row, 1).toString());
            classData.txtCVGrade.setText(model.getValueAt(row, 2).toString());
            classData.txtCVSubName.setText(model.getValueAt(row, 3).toString());
            classData.txtCVTime.setText(model.getValueAt(row, 4).toString());
            classData.txtCVDate.setText(model.getValueAt(row, 5).toString());
            classData.txtCVTeaName.setText(model.getValueAt(row, 6).toString());
            classData.txtCVClassFee.setText(model.getValueAt(row, 7).toString());

            try {
                Connection con = DatabaseConnection.getcon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select Teacher, Subject, Commision_Rate from class where Class_ID = '"+id+"'");
                while(rs.next()){
                    classData.txtCVTeaID.setText(rs.getString("Teacher"));
                    classData.txtCVSubID.setText(rs.getString("Subject"));
                    classData.txtCVCommision.setText(rs.getString("Commision_Rate"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Something went gone wrong...!", "Error", JOptionPane.ERROR_MESSAGE);
//                System.out.println(e);
            }
            classData.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Please select a row from table...");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        txtClassID.setText(null);
        txtClassName.setText(null);
        txtGrade.setText(null);
        txtSubID.setText(null);
        txtSubName.setText(null);
        txtTeacID.setText(null);
        txtTeacName.setText(null);
        txtTime.setText(null);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButton6ActionPerformed
    
//    Add new student coding
    String date;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(chkSun.isSelected()){
            date = "Sunday";
        }else if(chkMon.isSelected()){
            date = "Monday";
        }else if(chkTue.isSelected()){
            date = "Tuesday";
        }else if(chkWed.isSelected()){
            date = "Wednesday";
        }else if(chkThr.isSelected()){
            date = "Thursday";
        }else if(chkFri.isSelected()){
            date = "Friday";
        }else if(chkSat.isSelected()){
            date = "Saturday";
        }
        
        String sql = "insert into class (Class_ID, Class_Name, Grade, Schedule_date, Sche_time, Teacher, Subject, Class_Fee, Commision_Rate)"
                + " values('"+txtClassID.getText().toUpperCase()+"', '"+txtClassName.getText()+"', '"+txtGrade.getText()+"', '"+date+"',"
                + " '"+txtTime.getText()+"', '"+txtTeacID.getText()+"', '"+txtSubID.getText()+"', '"+txtAddClassFee.getText()+"', '"+txtAddComision.getText()+"')";
        try {
            Connection con = DatabaseConnection.getcon();
            PreparedStatement st = con.prepareStatement(sql);
            st.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Successfully created new class for "+txtSubName.getText());
            jButton6ActionPerformed(evt);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid value you entered... Please try again...");
        }
        
        
        Object row[] = new Object[8];
        row[0] = txtClassID.getText().toUpperCase();
        row[1] = txtClassName.getText();
        row[2] = txtGrade.getText();
        row[3] = txtSubID.getText();
        row[4] = txtTime.getText();
        row[5] = date;
        row[6] = txtTeacID.getText();
        row[7] = txtAddClassFee.getText();
        model.addRow(row);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtTeacIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeacIDKeyPressed
        try {
            Connection con = DatabaseConnection.getcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select Name_with_initials from teacher where Teacher_ID like '%"+txtTeacID.getText().toUpperCase()+"%'");
            while(rs.next()){
                txtTeacName.setText(rs.getString("Name_with_initials"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txtTeacIDKeyPressed

    private void txtSubIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubIDKeyPressed
        try {
            Connection con = DatabaseConnection.getcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select Subject_Name from subject where Subject_ID like '%"+txtSubID.getText().toUpperCase()+"%'");
            while(rs.next()){
                txtSubName.setText(rs.getString("Subject_Name"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_txtSubIDKeyPressed
//    Retrive admin password
    private String Login(){
        String aPass = null;
        Connection con = DatabaseConnection.getcon();
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery("select Password from user where AuthLevel = 'admin'");
            if(rs.next()){
                aPass = rs.getString("Password");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        return aPass;
    }
    
    
//    Hash function for encrypt user enter password.
    private static String hash(String data){
        String hashText = null;
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(data.getBytes());
            BigInteger number = new BigInteger(1, messageDigest);
            hashText = number.toString(16);
            while(hashText.length() <32){
                hashText = "0" + hashText;
            }
        } catch (Exception e) {
        }
     return hashText;
        
    }
//    Delete data from class
    private void btnClassesDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassesDeleteActionPerformed
        try {
            int row = tblClassData.getSelectedRow();
            String id = tblClassData.getValueAt(row, 0).toString();
            String sql = "delete from class where Class_ID = '"+id+"'";

            adminpassconfirm admin = new adminpassconfirm();
            admin.getSql(sql);
            admin.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Please select a row...");
        }
    }//GEN-LAST:event_btnClassesDeleteActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Classes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Classes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Classes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Classes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Classes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClassesDelete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkFri;
    private javax.swing.JCheckBox chkMon;
    private javax.swing.JCheckBox chkSat;
    private javax.swing.JCheckBox chkSun;
    private javax.swing.JCheckBox chkThr;
    private javax.swing.JCheckBox chkTue;
    private javax.swing.JCheckBox chkWed;
    private javax.swing.JPanel createClassPane;
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel overviewPane;
    private javax.swing.JTable tblClassData;
    private javax.swing.JTextField txtAddClassFee;
    private javax.swing.JTextField txtAddComision;
    private javax.swing.JTextField txtClassID;
    private javax.swing.JTextField txtClassName;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSubID;
    private javax.swing.JTextField txtSubName;
    private javax.swing.JTextField txtTeacID;
    private javax.swing.JTextField txtTeacName;
    private javax.swing.JFormattedTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
