/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package akura;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Pasindu01
 */
public class report extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    public report() {
        initComponents();
        
        setIcon();
        
        ExamReportTab.setVisible(true);
        jPanel4.setBackground(new Color(51,6,149));
        jPanel3.setBackground(new Color(51,51,51));
        jPanel5.setBackground(new Color(51,51,51));
        
        panelWelcomeExamReport.setVisible(true);
        PanelResultReport.setVisible(false);
        panelWelcomeClass.setVisible(true);
        classReportGene.setVisible(true);
        ClassTimeTablePane.setVisible(false);
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClassTimeTablePane = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        panelWelcomeClass = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        classReportGene = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        strtDate = new com.toedter.calendar.JDateChooser();
        ExamReportTab = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtRSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        PanelResultReport = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtRRegId = new javax.swing.JLabel();
        txtRFName = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtRNamewithInit = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtRNIC = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtRCat = new javax.swing.JLabel();
        txtRStream = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cmbRExamList = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        panelWelcomeExamReport = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        eDate = new com.toedter.calendar.JDateChooser();
        sDate = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Report Generation | Akura");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClassTimeTablePane.setBackground(new java.awt.Color(255, 255, 255));
        ClassTimeTablePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Class Time Table");
        ClassTimeTablePane.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1100, 30));

        panelWelcomeClass.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Find Date From Above Date Chooser Field");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("You Can Generate Colorfull Time Tables Here");

        javax.swing.GroupLayout panelWelcomeClassLayout = new javax.swing.GroupLayout(panelWelcomeClass);
        panelWelcomeClass.setLayout(panelWelcomeClassLayout);
        panelWelcomeClassLayout.setHorizontalGroup(
            panelWelcomeClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWelcomeClassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWelcomeClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelWelcomeClassLayout.setVerticalGroup(
            panelWelcomeClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWelcomeClassLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );

        ClassTimeTablePane.add(panelWelcomeClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 1080, 240));

        classReportGene.setBackground(new java.awt.Color(255, 255, 255));
        classReportGene.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Select Date");
        classReportGene.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 72, 30));

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Generate Time Table");
        jButton5.setBorderPainted(false);
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        classReportGene.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, -1, 36));

        strtDate.setBackground(new java.awt.Color(255, 255, 255));
        strtDate.setAutoscrolls(true);
        strtDate.setDateFormatString("EEEE");
        strtDate.setFocusable(false);
        strtDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        classReportGene.add(strtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 240, 30));

        ClassTimeTablePane.add(classReportGene, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 1070, 410));

        getContentPane().add(ClassTimeTablePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1120, 490));

        ExamReportTab.setBackground(new java.awt.Color(255, 255, 255));
        ExamReportTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        ExamReportTab.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 10, 490));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Exam Time Table");
        ExamReportTab.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 370, 30));

        txtRSearch.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtRSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRSearchKeyReleased(evt);
            }
        });
        ExamReportTab.add(txtRSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 360, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Find");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ExamReportTab.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 90, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("NIC / REG ID");
        ExamReportTab.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 120, 30));

        PanelResultReport.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Reg ID");

        txtRRegId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtRFName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Full Name");

        txtRNamewithInit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Name With Initials");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("NIC");

        txtRNIC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText("Category");

        txtRCat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtRStream.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setText("Stream");

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setText("Exams List");

        cmbRExamList.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Generate Report");
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelResultReportLayout = new javax.swing.GroupLayout(PanelResultReport);
        PanelResultReport.setLayout(PanelResultReportLayout);
        PanelResultReportLayout.setHorizontalGroup(
            PanelResultReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResultReportLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelResultReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(PanelResultReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PanelResultReportLayout.createSequentialGroup()
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbRExamList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(PanelResultReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelResultReportLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRRegId, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelResultReportLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRFName, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelResultReportLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRNamewithInit, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelResultReportLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelResultReportLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRCat, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelResultReportLayout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRStream, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        PanelResultReportLayout.setVerticalGroup(
            PanelResultReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelResultReportLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelResultReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRRegId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelResultReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRFName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelResultReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRNamewithInit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelResultReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelResultReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRCat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelResultReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRStream, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelResultReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(cmbRExamList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        ExamReportTab.add(PanelResultReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 630, 360));

        panelWelcomeExamReport.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Find Student Data From Above Search Field");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("You Can Generate Colorfull Reports Here");

        javax.swing.GroupLayout panelWelcomeExamReportLayout = new javax.swing.GroupLayout(panelWelcomeExamReport);
        panelWelcomeExamReport.setLayout(panelWelcomeExamReportLayout);
        panelWelcomeExamReportLayout.setHorizontalGroup(
            panelWelcomeExamReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWelcomeExamReportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWelcomeExamReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelWelcomeExamReportLayout.setVerticalGroup(
            panelWelcomeExamReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWelcomeExamReportLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );

        ExamReportTab.add(panelWelcomeExamReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 630, 360));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Exam Result Reports");
        ExamReportTab.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 510, 30));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setText("End Date");
        ExamReportTab.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 130, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setText("Start Date");
        ExamReportTab.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 130, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 255));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Generate Time Table");
        jButton4.setBorderPainted(false);
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        ExamReportTab.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, -1, 40));

        eDate.setBackground(new java.awt.Color(255, 255, 255));
        eDate.setFocusable(false);
        eDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ExamReportTab.add(eDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 290, 30));

        sDate.setBackground(new java.awt.Color(255, 255, 255));
        sDate.setFocusable(false);
        sDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ExamReportTab.add(sDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 290, 30));

        getContentPane().add(ExamReportTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1120, 490));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_card_payment_24px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Payment Report");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_google_classroom_32px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Class Time Table");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_exam_24px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Exam Report");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(430, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 600, 100, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Connection con = DatabaseConnection.getcon();
            JasperDesign jd = JRXmlLoader.load("G:\\Programme\\netbeans\\AkuraNew\\src\\report\\marks.jrxml");
            String sql = "select * from student inner join mark on student.Reg_ID = mark.Reg_ID inner join exam on mark.Exam_ID = exam.Exam_ID inner join class on exam.Class = class.Class_ID inner join subject on subject.Subject_ID = class.Subject inner join teacher on teacher.Teacher_ID = class.Teacher where student.Reg_ID = '"+txtRRegId.getText()+"'";
            try {
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                if(rs.next()){
                    String examYear = rs.getString("student.Exam_Year");
                    String sub = rs.getString("subject.Subject_Name");
                    String grade = rs.getString("class.Grade");
                    String mark = rs.getString("mark.Marks");
                    String teacher = rs.getString("teacher.Name_with_initials");
                    
                    
                    JRDesignQuery updateQuery = new JRDesignQuery();
                    updateQuery.setText(sql);

                    jd.setQuery(updateQuery);

                    HashMap param = new HashMap();
                    param.put("name", txtRFName.getText());
                    param.put("namewithInit", txtRNamewithInit.getText());
                    param.put("Reg_ID", txtRRegId.getText());
                    param.put("NIC", txtRNIC.getText());
                    param.put("Exam_Year", examYear);
                    param.put("Subject", sub);
                    param.put("Grade", grade);
                    param.put("Marks", mark);
                    param.put("Teacher", teacher);

                    JasperReport jr = JasperCompileManager.compileReport(jd);
                    JasperPrint jp = JasperFillManager.fillReport(jr, param, con);
                    JasperViewer jv = new JasperViewer(jp,false);
                    jv.setVisible(true);
                }
            } catch (Exception e) {
                System.out.println(e);
            }
            
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtRRegId.setText(null);
        txtRFName.setText(null);
        txtRNamewithInit.setText(null);
        txtRNIC.setText(null);
        txtRCat.setText(null);
        txtRStream.setText(null);
        cmbRExamList.removeAllItems();
        
        if(!"".equals(txtRSearch.getText())){
            try {
            Connection con = DatabaseConnection.getcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from student inner join mark on student.Reg_ID = mark.Reg_ID where student.Reg_ID like '%"+txtRSearch.getText()+"%' or student.NIC like '%"+txtRSearch.getText()+"&'");
            while(rs.next()){
                
                    txtRRegId.setText(rs.getString("student.Reg_ID"));
                    txtRFName.setText(rs.getString("student.Full_Name"));
                    txtRNamewithInit.setText(rs.getString("student.Name_with_initials"));
                    txtRNIC.setText(rs.getString("student.NIC"));
                    txtRCat.setText(rs.getString("student.Category"));
                    txtRStream.setText(rs.getString("student.Stream"));
                    cmbRExamList.addItem(rs.getString("mark.Exam_ID"));
                    if(cmbRExamList.getItemAt(0).equals("")){
                        JOptionPane.showMessageDialog(rootPane, "Can not find exams for "+txtRSearch.getText());
                    }

                    panelWelcomeExamReport.setVisible(false);
                    PanelResultReport.setVisible(true);
                
            }
            } catch (Exception e) {
                System.out.println(e);
            }
        }else{
            panelWelcomeExamReport.setVisible(true);
            PanelResultReport.setVisible(false);
            JOptionPane.showMessageDialog(rootPane, "Search field is can not be null", "Can Not Find Data" ,JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        ExamReportTab.setVisible(true);
        ClassTimeTablePane.setVisible(false);
        jPanel4.setBackground(new Color(51,6,149));
        jPanel3.setBackground(new Color(51,51,51));
        jPanel5.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        ClassTimeTablePane.setVisible(true);
        ExamReportTab.setVisible(false);
        jPanel4.setBackground(new Color(51,51,51));
        jPanel3.setBackground(new Color(51,51,51));
        jPanel5.setBackground(new Color(51,6,149));
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        ExamReportTab.setVisible(false);
        ClassTimeTablePane.setVisible(false);
        jPanel4.setBackground(new Color(51,51,51));
        jPanel3.setBackground(new Color(51,6,149));
        jPanel5.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Connection con = DatabaseConnection.getcon();
            JasperDesign jd1 = JRXmlLoader.load("G:\\Programme\\netbeans\\AkuraNew\\src\\report\\examTimeTable.jrxml");
            
//            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
//            String sdate1 = null, enddate1 = null;
//            try {
//                sdate1 = df.format(sDate.getDate());
//                enddate1 = df.format(eDate.getDate());
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(rootPane, "Please select a date range...");
//            }
//            Date sdate1 = new java.parse(sdate);
//            Date enddate1 = new SimpleDateFormat("yyyy-MM-dd").parse(enddate);
//            System.out.println(sdate1);
            
            String sql = "select * from exam inner join class on exam.Class = class.Class_ID inner join subject on class.Subject = subject.Subject_ID inner join teacher on class.Teacher = teacher.Teacher_ID "; //where ExamDate between '"+sdate+"' and '"+enddate+"'
            try {
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                String cid = null;
                String cname=null, grade = null, edate = null , etime = null, tname=null, sub = null;
                while(rs.next()){
                    cid = rs.getString("class.Class_ID");
                    cname = rs.getString("class.Class_Name");
                    grade = rs.getString("class.Grade");
                    edate = rs.getString("exam.ExamDate");
                    etime = rs.getString("exam.Time");
                    tname = rs.getString("teacher.Name_with_initials");
                    sub = rs.getString("subject.Subject_Name");
                }
                
                JRDesignQuery updateQuery1 = new JRDesignQuery();
                HashMap param = new HashMap();
                param.put("ID", cid);
                param.put("CNAME", cname);
                param.put("GRADE", grade);
                param.put("EDATE", edate);
                param.put("ETIME", etime);
                param.put("TNAME", tname);
                param.put("SUB", sub);

                updateQuery1.setText(sql);

                jd1.setQuery(updateQuery1);



                JasperReport jr = JasperCompileManager.compileReport(jd1);
                JasperPrint jp = JasperFillManager.fillReport(jr, param, con);
                JasperViewer jv = new JasperViewer(jp,false);
                jv.setVisible(true);
                
            } catch (Exception e) {
                System.out.println(e);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Connection con = DatabaseConnection.getcon();
            JasperDesign jd1 = JRXmlLoader.load("G:\\Programme\\netbeans\\AkuraNew\\src\\report\\classTimeTable.jrxml");
            
            SimpleDateFormat df = new SimpleDateFormat("EEEE");
            String sDate = null, date = null;
            
            String sql;
            try {
                date = strtDate.getDate().toString();
                sDate = df.format(strtDate.getDate());
                sql = "select * from timeTbl_class where Schedule_date = '"+sDate+"'";
            } catch (Exception e) {
                sql = "select * from timeTbl_class";
            }
            
            
            try {
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                
                
                JRDesignQuery updateQuery2 = new JRDesignQuery();
                

                updateQuery2.setText(sql);

                jd1.setQuery(updateQuery2);



                JasperReport jr = JasperCompileManager.compileReport(jd1);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JasperViewer jv = new JasperViewer(jp,false);
                jv.setVisible(true);
                
            } catch (Exception e) {
                System.out.println(e);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtRSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRSearchKeyReleased
        txtRRegId.setText(null);
        txtRFName.setText(null);
        txtRNamewithInit.setText(null);
        txtRNIC.setText(null);
        txtRCat.setText(null);
        txtRStream.setText(null);
        cmbRExamList.removeAllItems();
        
        if(!"".equals(txtRSearch.getText())){
            try {
            Connection con = DatabaseConnection.getcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from student inner join mark on student.Reg_ID = mark.Reg_ID where student.Reg_ID like '%"+txtRSearch.getText()+"%' or student.NIC like '%"+txtRSearch.getText()+"&'");
            while(rs.next()){
                
                    txtRRegId.setText(rs.getString("student.Reg_ID"));
                    txtRFName.setText(rs.getString("student.Full_Name"));
                    txtRNamewithInit.setText(rs.getString("student.Name_with_initials"));
                    txtRNIC.setText(rs.getString("student.NIC"));
                    txtRCat.setText(rs.getString("student.Category"));
                    txtRStream.setText(rs.getString("student.Stream"));
                    cmbRExamList.addItem(rs.getString("mark.Exam_ID"));
                    if(cmbRExamList.getItemAt(0).equals("")){
                        JOptionPane.showMessageDialog(rootPane, "Can not find exams for "+txtRSearch.getText());
                    }

                    panelWelcomeExamReport.setVisible(false);
                    PanelResultReport.setVisible(true);
                
            }
            } catch (Exception e) {
                System.out.println(e);
            }
        }else{
            panelWelcomeExamReport.setVisible(true);
            PanelResultReport.setVisible(false);
            JOptionPane.showMessageDialog(rootPane, "Search field is can not be null", "Can Not Find Data" ,JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtRSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClassTimeTablePane;
    private javax.swing.JPanel ExamReportTab;
    private javax.swing.JPanel PanelResultReport;
    private javax.swing.JPanel classReportGene;
    private javax.swing.JComboBox cmbRExamList;
    private com.toedter.calendar.JDateChooser eDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelWelcomeClass;
    private javax.swing.JPanel panelWelcomeExamReport;
    private com.toedter.calendar.JDateChooser sDate;
    private com.toedter.calendar.JDateChooser strtDate;
    private javax.swing.JLabel txtRCat;
    private javax.swing.JLabel txtRFName;
    private javax.swing.JLabel txtRNIC;
    private javax.swing.JLabel txtRNamewithInit;
    private javax.swing.JLabel txtRRegId;
    private javax.swing.JTextField txtRSearch;
    private javax.swing.JLabel txtRStream;
    // End of variables declaration//GEN-END:variables
}
