/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package akura;

import java.awt.Color;
import java.awt.Toolkit;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Pasindu01
 */
public class Teacher extends javax.swing.JFrame {

    /**
     * Creates new form Teacher
     */
    public Teacher() {
        initComponents();
        
        setIcon();
        
        tblTeacher.getTableHeader().setOpaque(false);
        tblTeacher.getTableHeader().setBackground(new Color(196, 88, 53));
        tblTeacher.getTableHeader().setForeground(new Color(255, 255, 255));
        tblTeacher.setRowHeight(25);
        
        paneOverview.setBackground(new Color(51,6,149));
        paneAddTeacher.setBackground(new Color(51,51,51));
        
        OverviewTab.setVisible(true);
        AddNewTeacherTab.setVisible(false);
        
        dataget();
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }
    
    public ArrayList<TeacherData> teacherData(){
        ArrayList<TeacherData> datalist = new ArrayList<>();
        
        try {
            Connection con = DatabaseConnection.getcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from teacher");
            TeacherData data;
            while(rs.next()){
                data = new TeacherData(rs.getString("Teacher_ID"), rs.getString("FullName"), rs.getString("Name_with_initials"), 
                        rs.getString("Address"), rs.getString("NIC"), rs.getString("Mobile_No"), rs.getString("Other"));
                datalist.add(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Something went gone wrong...!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return datalist;
    }
    
    public void dataget(){
        ArrayList<TeacherData> list = teacherData();
        model = (DefaultTableModel) tblTeacher.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getTeacher_ID();
            row[1] = list.get(i).getFullName();
            row[2] = list.get(i).getName_with_initials();
            row[3] = list.get(i).getAddress();
            row[4] = list.get(i).getNIC();
            row[5] = list.get(i).getMobile_No();
            model.addRow(row);
        }
    }
    
    public void search(String str){
        model = (DefaultTableModel) tblTeacher.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        tblTeacher.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        paneAddTeacher = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        paneOverview = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        OverviewTab = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTeacher = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnTeacherDelete = new javax.swing.JButton();
        AddNewTeacherTab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtAddFullName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAddNamewithinit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAddID = new javax.swing.JTextField();
        txtAddAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAddMobileNum = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAddNIC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rdoAddPrimary = new javax.swing.JRadioButton();
        rdoAddOL = new javax.swing.JRadioButton();
        rdoAddAL = new javax.swing.JRadioButton();
        rdoAddOther = new javax.swing.JRadioButton();
        txtAddSubject = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtAddClass = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtAddother = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Akura Student Management System | Teachers Information");
        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(1179, 670));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        paneAddTeacher.setBackground(new java.awt.Color(51, 51, 51));
        paneAddTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneAddTeacherMouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_teacher_30px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add New Teacher");

        javax.swing.GroupLayout paneAddTeacherLayout = new javax.swing.GroupLayout(paneAddTeacher);
        paneAddTeacher.setLayout(paneAddTeacherLayout);
        paneAddTeacherLayout.setHorizontalGroup(
            paneAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAddTeacherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        paneAddTeacherLayout.setVerticalGroup(
            paneAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneAddTeacherLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneAddTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap())
        );

        paneOverview.setBackground(new java.awt.Color(51, 51, 51));
        paneOverview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneOverviewMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_ratings_24px_1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Overview");

        javax.swing.GroupLayout paneOverviewLayout = new javax.swing.GroupLayout(paneOverview);
        paneOverview.setLayout(paneOverviewLayout);
        paneOverviewLayout.setHorizontalGroup(
            paneOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOverviewLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        paneOverviewLayout.setVerticalGroup(
            paneOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(608, Short.MAX_VALUE)
                .addComponent(paneOverview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paneAddTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paneOverview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneAddTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1179, 70));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 590, 100, 40));

        OverviewTab.setBackground(new java.awt.Color(255, 255, 255));
        OverviewTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(0, 0, 255));
        jButton10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("View");
        jButton10.setBorderPainted(false);
        jButton10.setFocusPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        OverviewTab.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 450, 105, 42));

        jButton4.setBackground(new java.awt.Color(0, 0, 255));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Update");
        jButton4.setBorderPainted(false);
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        OverviewTab.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 450, 105, 42));

        tblTeacher.setAutoCreateRowSorter(true);
        tblTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher ID", "Full Name", "Name With Initials", "Address", "NIC", "Mobile Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTeacher.setFillsViewportHeight(true);
        tblTeacher.setFocusable(false);
        tblTeacher.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblTeacher.setRowHeight(25);
        tblTeacher.setSelectionBackground(new java.awt.Color(102, 153, 255));
        tblTeacher.setShowVerticalLines(false);
        tblTeacher.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblTeacher);
        if (tblTeacher.getColumnModel().getColumnCount() > 0) {
            tblTeacher.getColumnModel().getColumn(0).setResizable(false);
            tblTeacher.getColumnModel().getColumn(5).setResizable(false);
        }

        OverviewTab.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1080, 380));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Enter Teacher ID or NIC");
        OverviewTab.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 180, 30));

        txtSearch.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        OverviewTab.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 470, 30));

        btnTeacherDelete.setBackground(new java.awt.Color(0, 0, 255));
        btnTeacherDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTeacherDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnTeacherDelete.setText("Delete");
        btnTeacherDelete.setBorderPainted(false);
        btnTeacherDelete.setFocusPainted(false);
        btnTeacherDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherDeleteActionPerformed(evt);
            }
        });
        OverviewTab.add(btnTeacherDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 105, 42));

        getContentPane().add(OverviewTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 79, 1130, 500));

        AddNewTeacherTab.setBackground(new java.awt.Color(255, 255, 255));
        AddNewTeacherTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Full Name");
        AddNewTeacherTab.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 25, 139, 28));

        txtAddFullName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAddFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddFullNameActionPerformed(evt);
            }
        });
        AddNewTeacherTab.add(txtAddFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 25, 316, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Name with initials");
        AddNewTeacherTab.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 80, 139, 28));

        txtAddNamewithinit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AddNewTeacherTab.add(txtAddNamewithinit, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 80, 316, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Teacher ID");
        AddNewTeacherTab.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 135, 139, 28));

        txtAddID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AddNewTeacherTab.add(txtAddID, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 135, 316, 30));

        txtAddAddress.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AddNewTeacherTab.add(txtAddAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 190, 316, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Address");
        AddNewTeacherTab.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 190, 139, 28));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Mobile Number");
        AddNewTeacherTab.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 245, 139, 28));

        txtAddMobileNum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AddNewTeacherTab.add(txtAddMobileNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 245, 316, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("NIC");
        AddNewTeacherTab.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 300, 139, 28));

        txtAddNIC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AddNewTeacherTab.add(txtAddNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 300, 316, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Stream");
        AddNewTeacherTab.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 348, 139, 28));

        rdoAddPrimary.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoAddPrimary);
        rdoAddPrimary.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rdoAddPrimary.setText("Primary");
        AddNewTeacherTab.add(rdoAddPrimary, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 348, -1, -1));

        rdoAddOL.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoAddOL);
        rdoAddOL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rdoAddOL.setText("O/L");
        AddNewTeacherTab.add(rdoAddOL, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 348, -1, -1));

        rdoAddAL.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoAddAL);
        rdoAddAL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rdoAddAL.setText("A/L");
        AddNewTeacherTab.add(rdoAddAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 348, -1, -1));

        rdoAddOther.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoAddOther);
        rdoAddOther.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rdoAddOther.setText("Other");
        AddNewTeacherTab.add(rdoAddOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 348, -1, -1));

        txtAddSubject.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AddNewTeacherTab.add(txtAddSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 400, 316, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Subject");
        AddNewTeacherTab.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 400, 139, 28));

        txtAddClass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AddNewTeacherTab.add(txtAddClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 448, 316, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Class");
        AddNewTeacherTab.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 448, 139, 28));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        AddNewTeacherTab.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 425, 86, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        AddNewTeacherTab.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1026, 425, 86, 40));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Other");
        AddNewTeacherTab.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 139, 28));

        txtAddother.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AddNewTeacherTab.add(txtAddother, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 316, 30));

        getContentPane().add(AddNewTeacherTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 89, 1130, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    TeacherDataView teacherview = new TeacherDataView();
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        teacherview.lblTitle.setText("Teacher Information");
        teacherview.jButton2.setVisible(false);
        
        try{
            model = (DefaultTableModel) tblTeacher.getModel();
            int row = tblTeacher.getSelectedRow();
            String idex = model.getValueAt(row, 0).toString();
            teacherview.txtTeacherID.setText(idex);
            teacherview.txtFullName.setText(model.getValueAt(row, 1).toString());
            teacherview.txtNameWithInitials.setText(model.getValueAt(row, 2).toString());
            teacherview.txtAddress.setText(model.getValueAt(row, 3).toString());
            teacherview.txtNIC.setText(model.getValueAt(row, 4).toString());
            teacherview.txtMobile.setText(model.getValueAt(row, 5).toString());

            try {
                Connection con = DatabaseConnection.getcon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from teacher where Teacher_ID='"+idex+"'");
                while(rs.next()){
                    teacherview.txtOther.setText(rs.getString("Other"));
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Something went gone wrong...!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            teacherview.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Please select a row from table...");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        teacherview.lblTitle.setText("Update Teacher Information");
        teacherview.jButton2.setVisible(true);
        try{
            model = (DefaultTableModel) tblTeacher.getModel();
            int row = tblTeacher.getSelectedRow();
            String idex = model.getValueAt(row, 0).toString();
            teacherview.txtTeacherID.setText(idex);
            teacherview.txtFullName.setText(model.getValueAt(row, 1).toString());
            teacherview.txtNameWithInitials.setText(model.getValueAt(row, 2).toString());
            teacherview.txtAddress.setText(model.getValueAt(row, 3).toString());
            teacherview.txtNIC.setText(model.getValueAt(row, 4).toString());
            teacherview.txtMobile.setText(model.getValueAt(row, 5).toString());

            try {
                Connection con = DatabaseConnection.getcon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from teacher where Teacher_ID='"+idex+"'");
                while(rs.next()){
                    teacherview.txtOther.setText(rs.getString("Other"));
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Something went gone wrong...!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            teacherview.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Please select a row from table...");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void paneOverviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneOverviewMouseClicked
        paneOverview.setBackground(new Color(51,6,149));
        paneAddTeacher.setBackground(new Color(51,51,51));
        
        OverviewTab.setVisible(true);
        AddNewTeacherTab.setVisible(false);
    }//GEN-LAST:event_paneOverviewMouseClicked

    private void paneAddTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneAddTeacherMouseClicked
        paneAddTeacher.setBackground(new Color(51,6,149));
        paneOverview.setBackground(new Color(51,51,51));
        
        OverviewTab.setVisible(false);
        AddNewTeacherTab.setVisible(true);
    }//GEN-LAST:event_paneAddTeacherMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtAddAddress.setText(null);
        txtAddClass.setText(null);
        txtAddFullName.setText(null);
        txtAddID.setText(null);
        txtAddMobileNum.setText(null);
        txtAddNIC.setText(null);
        txtAddNamewithinit.setText(null);
        txtAddSubject.setText(null);
        txtAddother.setText(null);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButton1ActionPerformed
    String stream =null;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(rdoAddPrimary.isSelected()){
            stream = "Primary";
        }else if(rdoAddOL.isSelected()){
            stream = "Ordinary Level";
        }else if(rdoAddAL.isSelected()){
            stream = "Advanced Level";
        }else if(rdoAddOther.isSelected()){
            stream = "Other Stream";
        }
        
        try {
            String sql = "insert into teacher values('"+txtAddID.getText().toUpperCase()+"', '"+txtAddFullName.getText().toUpperCase()+"',"
                    + "'"+txtAddNamewithinit.getText().toUpperCase()+"', '"+txtAddAddress.getText()+"',"
                    + " '"+txtAddNIC.getText()+"', '"+txtAddMobileNum.getText()+"',"
                    + "  '"+txtAddother.getText()+"')";
            Connection con = DatabaseConnection.getcon();
            PreparedStatement st = con.prepareStatement(sql);
            st.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Sucessfully added new teacher...");
            jButton1ActionPerformed(evt);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid you entered... Try again...");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtAddFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddFullNameActionPerformed
    DefaultTableModel model = new DefaultTableModel();
    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String text = txtSearch.getText().toUpperCase();
        search(text);
    }//GEN-LAST:event_txtSearchKeyReleased

    
    private String Login(){
        String aPass = null;
        Connection con = DatabaseConnection.getcon();
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery("select Password from user where AuthLevel = 'admin'");
            if(rs.next()){
                aPass = rs.getString("Password");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        return aPass;
    }
    
    
    private static String hash(String data){
        String hashText = null;
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(data.getBytes());
            BigInteger number = new BigInteger(1, messageDigest);
            hashText = number.toString(16);
            while(hashText.length() <32){
                hashText = "0" + hashText;
            }
        } catch (Exception e) {
        }
     return hashText;
        
    }
    private void btnTeacherDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherDeleteActionPerformed
//        model = (DefaultTableModel) tblTeacher.getModel();
        try {
            int row = tblTeacher.getSelectedRow();
            String id = tblTeacher.getValueAt(row, 0).toString();
            String sql = "delete from teacher where Teacher_ID = '"+id+"'";
            
            adminpassconfirm admin = new adminpassconfirm();
            admin.getSql(sql);
            admin.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Please select a row...");
        }
    }//GEN-LAST:event_btnTeacherDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel AddNewTeacherTab;
    public javax.swing.JPanel OverviewTab;
    public javax.swing.JButton btnTeacherDelete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JPanel paneAddTeacher;
    public javax.swing.JPanel paneOverview;
    private javax.swing.JRadioButton rdoAddAL;
    private javax.swing.JRadioButton rdoAddOL;
    private javax.swing.JRadioButton rdoAddOther;
    private javax.swing.JRadioButton rdoAddPrimary;
    private javax.swing.JTable tblTeacher;
    private javax.swing.JTextField txtAddAddress;
    private javax.swing.JTextField txtAddClass;
    private javax.swing.JTextField txtAddFullName;
    private javax.swing.JTextField txtAddID;
    private javax.swing.JTextField txtAddMobileNum;
    private javax.swing.JTextField txtAddNIC;
    private javax.swing.JTextField txtAddNamewithinit;
    private javax.swing.JTextField txtAddSubject;
    private javax.swing.JTextField txtAddother;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
