/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package akura;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Pasindu01
 */
public class viewClassData extends javax.swing.JFrame {

    /**
     * Creates new form viewClassData
     */
    public viewClassData() {
        initComponents();
        
        setIcon();
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblViewClassTitle = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCVClassID = new javax.swing.JTextField();
        txtCVClassName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCVGrade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCVTeaID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCVSubID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtCVTeaName = new javax.swing.JTextField();
        txtCVSubName = new javax.swing.JTextField();
        txtCVDate = new javax.swing.JFormattedTextField();
        txtCVTime = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCVClassFee = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCVCommision = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewClassTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblViewClassTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblViewClassTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblViewClassTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 619, 49));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Class ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 67, 184, 35));

        txtCVClassID.setEditable(false);
        txtCVClassID.setBackground(new java.awt.Color(255, 255, 255));
        txtCVClassID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txtCVClassID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 67, 344, 33));

        txtCVClassName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txtCVClassName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 115, 344, 33));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Class Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 115, 184, 35));

        txtCVGrade.setEditable(false);
        txtCVGrade.setBackground(new java.awt.Color(255, 255, 255));
        txtCVGrade.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txtCVGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 163, 344, 33));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Grade");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 163, 184, 35));

        txtCVTeaID.setEditable(false);
        txtCVTeaID.setBackground(new java.awt.Color(255, 255, 255));
        txtCVTeaID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txtCVTeaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 211, 344, 33));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Teacher ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 211, 184, 35));

        txtCVSubID.setEditable(false);
        txtCVSubID.setBackground(new java.awt.Color(255, 255, 255));
        txtCVSubID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txtCVSubID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 259, 344, 33));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Subject ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 259, 184, 35));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Schedule Data");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 307, 184, 35));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Schedule Time");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 361, 184, 35));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Teacher Name");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 414, 184, 35));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Subject Name");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 462, 184, 35));

        jButton5.setBackground(new java.awt.Color(255, 0, 51));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.setBorderPainted(false);
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, 99, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 255));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Update");
        jButton6.setBorderPainted(false);
        jButton6.setFocusPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 97, -1));

        txtCVTeaName.setEditable(false);
        txtCVTeaName.setBackground(new java.awt.Color(255, 255, 255));
        txtCVTeaName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txtCVTeaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 415, 344, 33));

        txtCVSubName.setEditable(false);
        txtCVSubName.setBackground(new java.awt.Color(255, 255, 255));
        txtCVSubName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txtCVSubName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 463, 344, 33));

        txtCVDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("EEEE"))));
        txtCVDate.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel1.add(txtCVDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 344, 33));

        txtCVTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("H:mm:ss"))));
        txtCVTime.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel1.add(txtCVTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 363, 225, 33));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("H:MM:SS");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 369, 100, -1));

        txtCVClassFee.setBackground(new java.awt.Color(255, 255, 255));
        txtCVClassFee.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txtCVClassFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 344, 33));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Class Fee");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 184, 35));

        txtCVCommision.setBackground(new java.awt.Color(255, 255, 255));
        txtCVCommision.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(txtCVCommision, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 344, 33));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setText("Commission Rate");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 184, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String sql = "update class set Class_Name = '"+txtCVClassName.getText()+"', Grade = '"+txtCVGrade.getText()+"',"
                + " Schedule_date = '"+txtCVDate.getText()+"', Sche_time = '"+txtCVTime.getText()+"', Teacher = '"+txtCVTeaID.getText()+"',"
                + " Subject = '"+txtCVSubID.getText()+"', Class_Fee = '"+txtCVClassFee.getText()+"', Commision_Rate = '"+txtCVCommision.getText()+"' where Class_ID = '"+txtCVClassID.getText()+"'";
        try {
            Connection con = DatabaseConnection.getcon();
            PreparedStatement st = con.prepareStatement(sql);
            st.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Sucessfully updated... ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid you entered... Please try again...");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewClassData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewClassData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewClassData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewClassData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewClassData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblViewClassTitle;
    public javax.swing.JTextField txtCVClassFee;
    public javax.swing.JTextField txtCVClassID;
    public javax.swing.JTextField txtCVClassName;
    public javax.swing.JTextField txtCVCommision;
    public javax.swing.JFormattedTextField txtCVDate;
    public javax.swing.JTextField txtCVGrade;
    public javax.swing.JTextField txtCVSubID;
    public javax.swing.JTextField txtCVSubName;
    public javax.swing.JTextField txtCVTeaID;
    public javax.swing.JTextField txtCVTeaName;
    public javax.swing.JFormattedTextField txtCVTime;
    // End of variables declaration//GEN-END:variables
}
